version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-benchmark
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: benchmarkdb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/
    command: mongod --storageEngine wiredTiger --wiredTigerCacheSizeGB 2 --noauth

volumes:
  mongodb_data:
